<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>WinUIApp</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win-$(Platform).pubxml</PublishProfile>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<WindowsPackageType>None</WindowsPackageType>

		<AssemblyName>Crunchyroll Notifier</AssemblyName>
		<AssemblyVersion>1.1.1</AssemblyVersion>
		<Version>$(AssemblyVersion)</Version>
		<Authors>Richard Whicker</Authors>
		<Company>TheDarkOrganism</Company>
		<RepositoryUrl>https://github.com/TheDarkOrganism/Crunchyroll-Notifier</RepositoryUrl>
		<Copyright>2025</Copyright>
	</PropertyGroup>

	<PropertyGroup Condition="'$(WindowsPackageType)'!='None'">
		<DefineConstants>PACKAGED_APP</DefineConstants>
	</PropertyGroup>

	<Target Name="CheckForProgram" BeforeTargets="BeforeBuild">
		<ItemGroup>
			<IncludesProgram Include="@(Compile)" Condition="'%(Filename)%(Extension)' == 'Program.cs'" />
		</ItemGroup>

		<PropertyGroup Condition="'@(IncludesProgram)' != ''">
			<DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
		</PropertyGroup>
	</Target>

	<PropertyGroup Condition="!$(Configuration.StartsWith('Debug'))">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Controls\CustomTimePicker.xaml" />
		<None Remove="Dialogs\TextInputDialog.xaml" />
		<None Remove="Settings.xaml" />
		<None Remove="Validation\ValidationTemplates.xaml" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.Extensions.Configuration" />
		<Using Include="Microsoft.Extensions.DependencyInjection" />
		<Using Include="Microsoft.Extensions.FileProviders" />
		<Using Include="Microsoft.Extensions.Hosting" />
		<Using Include="Microsoft.Extensions.Logging" />
		<Using Include="Microsoft.Extensions.Options" />
		<Using Include="Microsoft.UI.Xaml" />
		<Using Include="Microsoft.UI.Xaml.Controls" />
		<Using Include="Microsoft.UI.Xaml.Data" />
		<Using Include="Microsoft.Windows.AppNotifications" />
		<Using Include="Serilog.Events" />
		<Using Include="System.Collections" />
		<Using Include="System.Collections.ObjectModel" />
		<Using Include="System.ComponentModel" />
		<Using Include="System.ComponentModel.DataAnnotations" />
		<Using Include="System.Diagnostics" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="System.Globalization" />
		<Using Include="System.Reflection" />
		<Using Include="System.Text.Json" />
		<Using Include="System.Text.Json.Serialization" />
		<Using Include="System.Text.Json.Serialization.Metadata" />
		<Using Include="WinUIApp.Attributes" />
		<Using Include="WinUIApp.Enums" />
		<Using Include="WinUIApp.Models" />
		<Using Include="WinUIApp.Options" />
		<Using Include="WinUIApp.Validation" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\SplashScreen.scale-200.png" />
		<Content Include="Assets\LockScreenLogo.scale-200.png" />
		<Content Include="Assets\Square150x150Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
		<Content Include="Assets\StoreLogo.png" />
		<Content Include="Assets\Wide310x150Logo.scale-200.png" />
		<Content Include="Crunchyroll-Notifier.ico" />
	</ItemGroup>

	<ItemGroup Condition="'$(WindowsPackageType)'=='None'">
		<Content Remove="Assets/**" />
	</ItemGroup>

	<ItemGroup Condition="'$(WindowsPackageType)'!='None'">
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<!--
	Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
	Tools extension to be activated for this project even if the Windows App SDK Nuget
	package has not yet been restored.
  -->
	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="H.NotifyIcon.WinUI" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="9.0.6" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.6" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4188" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250513003" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
		<PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
		<PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Config.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
		<Page Update="Controls\CustomTimePicker.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Settings.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Dialogs\TextInputDialog.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Validation\ValidationTemplates.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<EmbeddedResource Include="LastUpdate.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>

	<!--
	Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
	Explorer "Package and Publish" context menu entry to be enabled for this project even if
	the Windows App SDK Nuget package has not yet been restored.
  -->
	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>

	<!-- Publish Properties -->
	<PropertyGroup>
		<PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
		<PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
		<PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
		<PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
		<ApplicationIcon>Crunchyroll-Notifier.ico</ApplicationIcon>
	</PropertyGroup>
</Project>